// <auto-generated />
namespace WpfPizzaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddTabelaBebidas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTabelaBebidas));
        
        string IMigrationMetadata.Id
        {
            get { return "201909261756199_AddTabelaBebidas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
